### ISSUE TITLE
About input data

### ISSUE THREAD

**Issue by tomfisher** [mcyeh/mstamp#1]
Hi, 

I am wondering input for mstramp or mstomp function has to be z-normalized. I tested with some un-normalized data and it seemed that we have to z-normalized data since a warning will be thrown for un-normalized data: 
`
mstamp_stomp.py:127: RuntimeWarning: invalid value encountered in sqrt
  matrix_profile = np.sqrt(matrix_profile)
`

Am I right? 

Thanks.

**Comment by JaKasb** [comment]
The MASS algorithm has a built-in z-normalisation by subtracting the mean and dividing by the standard deviation. Therefore it should not be required to normalise the input data.

**Comment by mcyeh** [comment]
Hi @tomfisher,

No, you do not need to z-normalized the data as mentioned by @JaKasb. 

One possible reason for this warning is that there might be some negative values in matrix profile prior to np.sqrt(matrix_profile). Add the line matrix_profile[matrix_profile < 0] = 0 before np.sqrt(matrix_profile) may solve the problem. 

I am currently traveling, so I did not tested this solution myself. Let me know how this fix works for you.

Thanks,

**Comment by tomfisher** [comment]
@mcyeh I did what you told, but it did not work since the resulted diagram looks really different from the one with z-norm pre-processing. In addition, I just took a look at the code and did not find z-norm related code in MASS implementation. Maybe I am wrong about this since I din't read details about MASS.

**Comment by tomfisher** [comment]
@mcyeh Do you need my data to verify the issue?

**Comment by mcyeh** [comment]
@tomfisher It would be really helpful if you could share the data with me

**Comment by tomfisher** [comment]
Sure.  Here (https://github.com/mcyeh/mstamp/files/1503714/test.txt) is a csv file containing accelerometer values at 25Hz [test.txt]

**Comment by JaKasb** [comment]
Works fine for me.

However I reproduced the warning by pure coincidence:
1. Execute stamp and wait for the progress bar to appear
2. Interrupt the Ipython Kernel using Ipython Notebook's "Stop Button"
3. Wait until the progress bar is full and the warning will appear

I don't think it is a bug if the code is not "interrupt safe".

Output of working notebook:

```python
import numpy as np
from mstamp_stamp import mstamp as mstamp_stamp
from mstamp_stomp import mstamp as mstamp_stomp
```


```python
x = np.loadtxt("test.txt", delimiter=',')
x.shape
```




    (4525, 3)




```python
mat_pro_1, pro_idx_1 = mstamp_stamp(x.T, 25)
```

    Progress [##################################################] 100.0%      0.0 sec


    
    



```python
mat_pro_2, pro_idx_2 = mstamp_stomp(x.T, 25)
```

    Progress [##################################################] 100.0%      0.0 sec


```python
np.allclose(mat_pro_1, mat_pro_2)
```




    True




```python
np.allclose(pro_idx_1, pro_idx_2)
```




    True

**Comment by tomfisher** [comment]
@JaKasb  your code works fine. My failure case was that I load the data via pandas which does not convert them into float types internally.
