### ISSUE TITLE
`que_sig` discarded while looping over dimensions

### ISSUE THREAD

**Issue by CharlesJQuarra** [mcyeh/mstamp#6]
In the python implementation of the `stamp` algorithm, I noticed that while looping and computing `_mass` over dimensions, only the `que_sig` over the last dimension is used on line 90:

```
         for j in range(n_dim):
            que = seq[j, i:i + sub_len]
            dist_profile[j, :], que_sig = _mass(
                seq_freq[j, :], que, seq_len, sub_len,
                seq_mu[j, :], seq_sig[j, :])

        if skip_loc[i] or np.any(que_sig < _EPS):
            continue
```

https://github.com/mcyeh/mstamp/blob/master/Python/mstamp_stamp.py lines 84 - 91

Is this discarding intentional, or is just that the current implementation is not using it any further?

**Comment by mcyeh** [comment]
Hi @CharlesJQuarra ,

Thanks for pointing it out! I have fixed this problem. Now all dimensions in `que_sig` are checked.

Michael
