### ISSUE TITLE
Bug in cumsum

### ISSUE THREAD

**Issue by seanlaw** [mcyeh/mstamp#7]
In `mstamp_stomp.py`, you have written:

```
dist_profile_dim = np.argsort(dist_profile, axis=0)
dist_profile_sort = np.sort(dist_profile, axis=0)
dist_profile_cumsum = np.zeros(sub_num)
for j in range(n_dim):
    dist_profile_cumsum += dist_profile_sort[j, :]
    dist_profile_mean = dist_profile_cumsum / (j + 1)
```

However, `dist_profile_sort` are actually squared distances! Thus, I believe that your `cumsum` is wrong or, at least, inconsistent from your paper. For example, if `dist_profile_sort` was:
```
[[1, 1, 1],
 [1, 4, 9]]
```

Then, in the `for` loop when `j = 0`:
```
dist_profile_cumsum = [1, 1, 1]
dist_profile_mean = [1, 1, 1]
```

When `j = 1`:
```
dist_profile_cumsum = [2, 5, 10]
dist_profile_mean = [1, 2.5, 5]
```

One would think that the `dist_profile_mean` (which is still a squared distance) could be evaluated by taking the square root and you would get:
```
[1, 1.5811, 2.236]
```

However, when we compare this with using straight distances (and not squared distances), we see that the above is not correct when `j = 1`:
```
dist_profile_cumsum = [2, 3, 4]
dist_profile_mean = [1, 1.5, 2]
```

Notice that `[1, 1.5811, 2.236]` is different from `[1, 1.5, 2]`! To be more precise, the problem is that you've computed the mean of the squared distances and then, later, you take the square root. This is different from mean of the summed distances.

The should be:

```
dist_profile = np.sqrt(dist_profile)  # Added this line 

dist_profile_dim = np.argsort(dist_profile, axis=0)
dist_profile_sort = np.sort(dist_profile, axis=0)
dist_profile_cumsum = np.zeros(sub_num)
for j in range(n_dim):
    dist_profile_cumsum += dist_profile_sort[j, :]
    dist_profile_mean = dist_profile_cumsum / (j + 1)
    update_pos = dist_profile_mean < matrix_profile[j, :]
    profile_index[j, update_pos] = i
    matrix_profile[j, update_pos] = dist_profile_mean[update_pos]
    if return_dimension:
        profile_dimension[j][:, update_pos] = \
            dist_profile_dim[:j + 1, update_pos]

# matrix_profile = np.sqrt(matrix_profile)  # Removed this line
```

**Comment by mcyeh** [comment]
Nice catch. I will fix this when I get time.

**Comment by mcyeh** [comment]
It is fixed!
